/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_requestOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["MeController_updateProfile"];
        trace?: never;
    };
    "/me/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeController_verificationStatus"];
        put?: never;
        post: operations["MeController_submitVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["VenuesController_listSports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["VenuesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["VenuesController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courts/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["VenuesController_slots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BookingsController_hold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BookingsController_mine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentsController_payInfo"];
        put?: never;
        post: operations["PaymentsController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendor/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentsController_access"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendor/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentsController_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendor/payments/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PaymentsController_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vendor/payments/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PaymentsController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            code: string;
            message: string;
        };
        OtpRequest: {
            /** @example 0300 1234567 */
            phone: string;
        };
        OtpSent: {
            resendInSeconds: number;
        };
        OtpVerify: {
            phone: string;
            /** @example 123456 */
            code: string;
        };
        SignedIn: {
            accessToken: string;
            /** Format: date-time */
            accessExpiresAt: string;
            refreshToken: string;
            /** Format: date-time */
            refreshExpiresAt: string;
            isNewUser: boolean;
            user: components["schemas"]["User"];
        };
        User: {
            /** Format: uuid */
            id: string;
            name: string | null;
            /** @enum {string} */
            status: "pending_verification" | "active" | "suspended" | "banned" | "deleted";
            isMinor: boolean;
            countryCode: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        Tokens: {
            accessToken: string;
            /** Format: date-time */
            accessExpiresAt: string;
            refreshToken: string;
            /** Format: date-time */
            refreshExpiresAt: string;
        };
        ProfileUpdate: {
            name: string;
            /**
             * Format: date
             * @example 2000-01-31
             */
            dob: string;
            /** @enum {string} */
            gender: "male" | "female" | "other" | "prefer_not_to_say";
            city: string;
        };
        VerificationStatus: {
            /** @enum {string} */
            status: "none" | "pending" | "approved" | "rejected";
            rejectionReason: string | null;
            /** @enum {string} */
            docType: "cnic" | "b_form";
            /** @enum {string} */
            requiredAt: "signup" | "before_participation";
        };
        Sport: {
            slug: string;
            name: string;
        };
        VenueSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            city: string;
            address: string;
            facilities: string[];
            sports: string[];
            courtCount: number;
            currency: string;
            /** @description Lowest hourly price, minor units */
            fromPricePerHour: number | null;
        };
        Venue: {
            /** Format: uuid */
            id: string;
            name: string;
            city: string;
            address: string;
            facilities: string[];
            currency: string;
            rules: string | null;
            timezone: string;
            courts: {
                /** Format: uuid */
                id: string;
                name: string;
                surface: string | null;
                slotMinutes: number;
                sports: string[];
            }[];
            policy: components["schemas"]["VenuePolicy"];
            paymentMethods: ("jazzcash" | "easypaisa" | "bank_transfer" | "cash")[];
        };
        VenuePolicy: {
            /** @enum {string} */
            advanceType: "fixed" | "percentage" | "none";
            /** @description Basis points if percentage, minor units if fixed */
            advanceValue: number;
            cancelRefund: boolean;
            cancelWindowHours: number;
            noShowRefund: boolean;
        };
        CourtSlots: {
            currency: string;
            slots: {
                /** Format: date-time */
                startAt: string;
                /** Format: date-time */
                endAt: string;
                /** @description Minor units */
                price: number;
                available: boolean;
            }[];
        };
        HoldRequest: {
            /** Format: uuid */
            courtId: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
        };
        Hold: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "held" | "pending_payment" | "confirmed" | "completed" | "cancelled" | "no_show" | "expired";
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            currency: string;
            /** @description Minor units */
            total: number;
            /** @description Minor units */
            advanceDue: number;
            /** Format: date-time */
            holdExpiresAt: string | null;
            policy: {
                /** @enum {string} */
                advanceType: "fixed" | "percentage" | "none";
                advanceValue: number;
                cancelRefund: boolean;
                cancelWindowHours: number;
                noShowRefund: boolean;
            };
        };
        MyBooking: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "held" | "pending_payment" | "confirmed" | "completed" | "cancelled" | "no_show" | "expired";
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            currency: string;
            /** @description Minor units */
            total: number;
            /** @description Minor units */
            advanceDue: number;
            /** Format: date-time */
            holdExpiresAt: string | null;
            policy: {
                /** @enum {string} */
                advanceType: "fixed" | "percentage" | "none";
                advanceValue: number;
                cancelRefund: boolean;
                cancelWindowHours: number;
                noShowRefund: boolean;
            };
            /** Format: date-time */
            paymentDeadlineAt: string | null;
            court: {
                /** Format: uuid */
                id: string;
                name: string;
            };
            venue: {
                /** Format: uuid */
                id: string;
                name: string;
                city: string;
                timezone: string;
            };
        };
        PayInfo: {
            /** @enum {string} */
            status: "held" | "pending_payment" | "confirmed" | "completed" | "cancelled" | "no_show" | "expired";
            currency: string;
            timezone: string;
            total: number;
            advanceDue: number;
            /** Format: date-time */
            holdExpiresAt: string | null;
            /** Format: date-time */
            paymentDeadlineAt: string | null;
            payAtVenueAllowed: boolean;
            accounts: {
                /** @enum {string} */
                method: "jazzcash" | "easypaisa" | "bank_transfer" | "cash";
                accountTitle: string;
                accountNumber: string | null;
                bankName: string | null;
            }[];
            payments: {
                /** @enum {string} */
                status: "pending" | "submitted" | "confirmed" | "rejected" | "refunded" | "void";
                /** @enum {string|null} */
                method: "jazzcash" | "easypaisa" | "bank_transfer" | "cash" | null;
                txnReference: string | null;
            }[];
        };
        PaymentSubmission: {
            /** @enum {string} */
            method: "jazzcash" | "easypaisa" | "bank_transfer" | "cash";
            txnReference?: string;
        };
        PaymentResult: {
            /** @enum {string} */
            status: "held" | "pending_payment" | "confirmed" | "completed" | "cancelled" | "no_show" | "expired";
            /** Format: date-time */
            paymentDeadlineAt: string | null;
        };
        VendorAccess: {
            vendors: {
                /** Format: uuid */
                id: string;
                businessName: string;
                branches: {
                    /** Format: uuid */
                    id: string;
                    name: string;
                }[];
            }[];
        };
        PaymentToCheck: {
            /** Format: uuid */
            id: string;
            /** @enum {string|null} */
            method: "jazzcash" | "easypaisa" | "bank_transfer" | "cash" | null;
            txnReference: string | null;
            advanceAmount: number;
            /** Format: date-time */
            submittedAt: string;
            playerName: string | null;
            court: string;
            branch: {
                name: string;
                timezone: string;
            };
            booking: {
                /** Format: uuid */
                id: string;
                /** @enum {string} */
                status: "held" | "pending_payment" | "confirmed" | "completed" | "cancelled" | "no_show" | "expired";
                /** Format: date-time */
                startAt: string;
                /** Format: date-time */
                endAt: string;
                currency: string;
                total: number;
                /** Format: date-time */
                holdExpiresAt: string | null;
                /** Format: date-time */
                paymentDeadlineAt: string | null;
            };
        };
        PaymentHandled: {
            /** Format: uuid */
            id: string;
        };
        RejectPayment: {
            reason: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_requestOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpSent"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    AuthController_verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerify"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedIn"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tokens"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    MeController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    MeController_verificationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    MeController_submitVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @example 99999-9999999-9 */
                    docNumber: string;
                    /** Format: binary */
                    front: string;
                    /** Format: binary */
                    back: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationStatus"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    VenuesController_listSports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sport"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    VenuesController_list: {
        parameters: {
            query?: {
                sport?: string;
                city?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VenueSummary"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    VenuesController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Venue"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    VenuesController_slots: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourtSlots"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    BookingsController_hold: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hold"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    BookingsController_mine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyBooking"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    PaymentsController_payInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayInfo"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    PaymentsController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentSubmission"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    PaymentsController_access: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorAccess"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    PaymentsController_queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentToCheck"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    PaymentsController_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentHandled"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    PaymentsController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectPayment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentHandled"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
